export const TEST_IDS = {
  auth: {
    dashboard: 'auth.dashboard',
    emailInput: 'auth.email-input',
    loginTab: 'auth.login-tab',
    logoutButton: 'auth.logout-button',
    nameInput: 'auth.name-input',
    passwordInput: 'auth.password-input',
    registerTab: 'auth.register-tab',
    socialAppleButton: 'auth.social-apple-button',
    socialGoogleButton: 'auth.social-google-button',
    submitButton: 'auth.submit-button',
    userEmail: 'auth.user-email',
  },
  components: {
    catalog: 'components.catalog',
    title: 'components.title',
  },
  details: {
    backButton: 'details.back-button',
    openButton: 'details.open-button',
    screen: 'details.screen',
  },
  paywall: {
    empty: 'paywall.empty',
    error: 'paywall.error',
    loading: 'paywall.loading',
    planOption: 'paywall.plan-option',
    profileButton: 'paywall.profile-button',
    purchaseButton: 'paywall.purchase-button',
    redeemOfferCodeButton: 'paywall.redeem-offer-code-button',
    restoreButton: 'paywall.restore-button',
    screen: 'paywall.screen',
  },
  screen: {
    backButton: 'screen.back-button',
  },
  categories: {
    addCategoryButton: 'categories.add-category-button',
    addSubcategoryButton: 'categories.add-subcategory-button',
    categoryNameInput: 'categories.category-name-input',
    screen: 'categories.screen',
    subcategoryNameInput: 'categories.subcategory-name-input',
  },
  overview: {
    saveStartingBalanceButton: 'overview.save-starting-balance-button',
    screen: 'overview.screen',
    startingBalanceInput: 'overview.starting-balance-input',
  },
  tabs: {
    categoriesTab: 'tabs.categories',
    componentsTab: 'tabs.components',
    overviewTab: 'tabs.overview',
    profileTab: 'tabs.profile',
    transactionsTab: 'tabs.transactions',
  },
  transactions: {
    addButton: 'transactions.add-button',
    amountInput: 'transactions.amount-input',
    noteInput: 'transactions.note-input',
    screen: 'transactions.screen',
  },
} as const;
